### ISSUE TITLE
bug: Layout is scrambled in the beginning for multiple seconds

### ISSUE THREAD

**Issue by guerda** [rstockm/mastowall#11]
If you open the Mastowall with a hashtag (I tested it out with [#antifasticker](https://rstockm.github.io/mastowall/?hashtags=antifasticker&server=https://chaos.social)) the layout is scrambled for the first seconds. It happens with other tags, too.

![Cards of toots which are not arranged correctly.](https://github.com/rstockm/mastowall/assets/230782/ce34d1c7-a5b8-429f-b9fb-4b9d6c261f23)

It looks like the first call of `https://<instance>/api/v1/timelines/tag/antifasticker?limit=20` must be finished, before the layout is applied. 
![Network inspector in Firefox, where first all calls for assets are shown. At the end, the mentioned api call is finished](https://github.com/rstockm/mastowall/assets/230782/9a837def-71bc-4c5b-9a0d-4b996324bfbe)

After that initial call is finished, the layout is correctly applied.
Can this be fixed somehow?

**Comment by rstockm** [comment]
Should be way better with this fix:

https://github.com/rstockm/mastowall/commit/6c43c6ebdd3bc82dffd17c06ee35d2ccaadadfce

3 seconds after initial loading the layout is rearranged, then every 10 seconds like before.
