### ISSUE TITLE
Layoutoption: Single column

### ISSUE THREAD

**Issue by forenta** [rstockm/mastowall#9]
I get it, it's called Masto*wall* and is probably based on some bird software I haven't come across. But I still just want a timeline.

Currently I use Fediwall/Mastowall in the sidebar of Vivaldi and Edge to get a glimpse of the wider Fediverse with hashtags that interest me on an ongoing basis. That's all I want.

Is there another corresponding service I've missed? Basically, I want the bar not to turn into a wall at >500px width (or however much that is), but just leave the outer sides blank at more than x pixels tab width. Would this be feasible or of interest?

**Comment by rstockm** [comment]
I see you point, but you should give the "enhanced web interface" of Mastodon a try:

<img width="837" alt="image" src="https://github.com/rstockm/mastowall/assets/3195116/334dd7bc-e3d2-48ab-85c8-20597f398fad">

(sorry for the german screenshot).
This gives you a multi-column view, and one of them can be a hashtag - just like my wall in a 1-column-view would behave llike.
